version: '3.8'
services:
  localstack:
    image: localstack/localstack:latest
    environment:
      SERVICES: dynamodb
    ports:
      - 4566:4566
  dynamodb-admin-test:
    container_name: dynamodb-admin-test
    image: aaronshaf/dynamodb-admin:latest
    environment:
      - DYNAMO_ENDPOINT=localstack:4566
    ports:
      - 8001:8001
    depends_on:
      - localstack